<% PASSWORD_FILE = File.join(RAILS_ROOT, '..', '..', 'shared', 'config', 'dbpassword') %>

development:
  adapter: postgresql
  database: operatorserver_development
  username: postgres
  password: postgres
  
test: &TEST
  adapter: postgresql
  database: operatorserver_test
  username: postgres
  password: postgres
  
staging:
  adapter: postgresql
  database: operatorserver_staging
  username: pgsql
  password: <%= File.read(PASSWORD_FILE).chomp if File.readable? PASSWORD_FILE %>
  
production:
  adapter: postgresql
  database: operatorserver_production
  username: pgsql
  password: <%= File.read(PASSWORD_FILE).chomp if File.readable? PASSWORD_FILE %>

cucumber:
  <<: *TEST
